### ISSUE TITLE
Feedback on the Content Guide's Capitalization Guidelines

### ISSUE THREAD

**Issue by bsonefeld** [carbon-design-system/design-system-website#1]
dhudlow commented on Mar 9 • edited

1. The guidelines for capitalizing words in headline-style capitalization list words which are most commonly prepositions, such as "before" and "after" as examples of words which **should** be capitalized, but then designates prepositions as words which **should not** be capitalized.
   
   In general, I think the guidelines for headline-style capitalization are confusing. I'm not convinced that these guidelines should require the reader to understand the finer points of parts of speech at all (especially considering the diversity of teams at IBM), but even if they remain driven by parts of speech, I think each part of speech (e.g., nouns, verbs, etc.) mentioned should list examples or even (where possible, such as with articles) list the words comprehensively.
   
   On the subject of prepositions in particular, I favor style guides which specify that certain kinds of words (usually nouns, verbs, adjectives, adverbs, and pronouns) always be capitalized while also specifying that any word longer than three letters be capitalized. This results in a standard where, for example, "in" is not capitalized whereas "between" is.
2. I think we should consider using headline-style capitalization for button labels, menu labels, menu items, and other "actions." This follows the style used by Apple and Microsoft operating systems. 
   
   I realize this absolutely is a matter of taste, but I submit as evidence that many of us are hardwired to prefer headline-style capitalization for actions (due to its use in major operating systems) that two of the common actions listed in the Content Guide glossary are erroneously in headline-style case: "Get Help" and "Save As..."
   
   (While on the subject of that "Save As...", I should mention that the ellipsis should probably be dropped from it, and from "Import..." and "Export..." Windows and macOS have very explicit conventions for what an ellipsis at the end of a command means, and I doubt we're dedicating ourselves to following any such convention. If we are, that's fine too, but it should be documented.)

**Comment by bsonefeld** [comment]
cdmauney commented on Mar 10
Thanks for the feedback. Will look into this.

**Comment by tay-aitken** [comment]
Moved this issue to an internal repo so that the content team could be included on the discussion. Closing this issue as the discussion will continue there.
