### ISSUE TITLE
Change link text from "here" to "unpkg CDN" so that link text can stand alone

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/design-system-website#109]
On the [Developer getting started page](http://www.carbondesignsystem.com/getting-started/developers) the following sentence contains a link that simply has the word "here" as its link text:
> See all files from carbon-components available on unpkg CDN [here](https://unpkg.com/carbon-components/).

For better accessibility, WCAG 2.0 SC 2.4.4 recommends the following:
> 2.4.4 Link Purpose (In Context): The purpose of each link can be determined from the link text alone

Screen readers can list the links on a page, allowing screen reader users to jump directly to a specific link.
If presented with a link labelled "here", a screen reader user cannot know where that link will take them.

**Comment by marijohannessen** [comment]
Resolved
