### ISSUE TITLE
Minor Search fixes for accessibility

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/design-system-website#114]
The Search field has 2 accessibility problems:
1) There are 2 elements with `role="search"`, and there should only be one in this case (they are both part of the same search landmark); so the parent div should keep the `role="search"`, and its input child does not need it.
2) The input needs a label (note that placeholder is not considered to be a label, because it is often used as an example of what to fill in).

**Comment by carmacleod** [comment]
In case it's helpful, here's the [W3C example of a Search landmark](http://w3c.github.io/aria-practices/examples/landmarks/search.html) (including description).

**Comment by marijohannessen** [comment]
Thanks for fixing this! 👍
