### ISSUE TITLE
Some language-css tokens do not meet color contrast requirement

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/design-system-website#116]
Some of the tokens in language-css styles do not meet the [WCAG 2.0 AA color contrast requirement of 4.5:1](https://www.w3.org/TR/WCAG21/#contrast-minimum).

For example:
1) `token selector` (changing selector foreground to almost identical-looking #5c71c8 will pass):
![token selector in debugger](https://user-images.githubusercontent.com/3331913/34735569-e7460d3a-f53d-11e7-9bce-fd6f730c65d6.png)

2) `token atrule` (changing to #0081a2 will pass):
![token atrule in debugger](https://user-images.githubusercontent.com/3331913/34735736-7460cd40-f53e-11e7-94b1-dec983943096.png)

3) `token property` (changing to #9d6e00 will pass):
![token property in debugger](https://user-images.githubusercontent.com/3331913/34736060-b15763e8-f53f-11e7-939c-362573a0f583.png)

4) `token string` (changing to #0081a2 will pass... same as for atrule, above):
![token string in debugger](https://user-images.githubusercontent.com/3331913/34736125-da6d4bf8-f53f-11e7-9fc3-980bfa8b76d9.png)

**Comment by carmacleod** [comment]
I'm not comfortable providing a PR for this one, because I don't know the rationale behind the current color choices. However, if you like, I can make the above changes in syntax.css for the following styles:
.token.property
.token.string
.token.selector
.token.atrule (and .token.statement and .token.regex because they are in the same css ruleset)

Of course, I didn't test all of the token styles - only the ones that are on the developer getting started page. If I see others, I will add them to this issue.

I also see that the same set of css token selectors is also in file prism.css (with different color values), and I don't know if they need to be kept in sync with any changes in syntax.css.

**Comment by carmacleod** [comment]
Also:
.token.variable needs to change foreground to #007cbf
.token.statement.keyword needs to change foreground to #0081a2
.token.function needs to change foreground to #d9375c
.token.comment needs to change foreground to #6f7590

**Comment by marijohannessen** [comment]
@tay-aitken Could you look into which colors we can change these to?

**Comment by tay-aitken** [comment]
@tw15egan didn't we pull in a theme for this? or did we create our own theme? I vaguely remember choosing colors but can't remember if we pulled from a palette of preset colors.

**Comment by tw15egan** [comment]
We used a theme but modified the colors a little bit

**Comment by bsonefeld** [comment]
@tay-aitken will definitely be something to consider as we redesign the Component page.

**Comment by aagonzales** [comment]
related issue: https://github.com/carbon-design-system/design-system-website/issues/194

**Comment by alisonjoseph** [comment]
@tay-aitken 
```
.token.comment,
.token.prolog,
.token.doctype,
.token.cdata {
  color: #898ea4;
}

.token.punctuation {
  color: #cdd1d4;
}

.token.operator {
  color: #cdd1d4;
}

.token.boolean,
.token.number {
  color: #006456;
}

.token.property {
  color: #c08b30;
}

.token.tag {
  color: #5b8121;
}

.token.string {
  color: #22a2c9;
}

.token.selector {
  color: #6679cc;
}

.token.attr-name {
  color: #c22dd5;
}

.token.entity,
.token.url,
.language-css .token.string,
.style .token.string {
  color: #22a2c9;
}

.token.attr-value,
.token.keyword,
.token.control,
.token.directive,
.token.unit {
  color: #006456;
}

.token.statement,
.token.regex,
.token.atrule {
  color: #22a2c9;
}

.token.placeholder,
.token.variable {
  color: #3d8fd1;
}

.token.important {
  color: #c94922;
}

```

**Comment by tay-aitken** [comment]
## Final Color Changes

**Color Updates**
Made the following color changes for accessibility and variety:
![as is](https://user-images.githubusercontent.com/29312997/40022004-532f2bac-578c-11e8-9397-8111c895a4af.png)


**Code Update**
The updated code should look like this. I ended up switching some of the color roles around too so they made a bit more sense. @alisonjoseph let me know if you want me to make a separate PR change for this or if you want to do it with your code snippet work. Note that I also changes the highlight color to `rgba(85, 150, 230 , .1)`, that change is not reflected in the chart above.


```
/*

Name:       Base16 Atelier Sulphurpool Light
Author:     Bram de Haan (http://atelierbram.github.io/syntax-highlighting/atelier-schemes/sulphurpool)

Prism template by Bram de Haan (http://atelierbram.github.io/syntax-highlighting/prism/)
Original Base16 color scheme by Chris Kempson (https://github.com/chriskempson/base16)

*/
code[class*='language-'],
pre[class*='language-'] {
  font-family: 'ibm-plex-mono', Menlo, Monaco, 'Andale Mono WT', 'Andale Mono',
    'Lucida Console', 'Lucida Sans Typewriter', 'DejaVu Sans Mono',
    'Bitstream Vera Sans Mono', 'Liberation Mono', 'Nimbus Mono L',
    'Courier New', Courier, monospace;
  font-size: 14px;
  line-height: 1.375;
  direction: ltr;
  text-align: left;
  white-space: pre;
  word-spacing: normal;
  word-break: normal;
  -moz-tab-size: 4;
  -o-tab-size: 4;
  tab-size: 4;
  -webkit-hyphens: none;
  -moz-hyphens: none;
  -ms-hyphens: none;
  hyphens: none;
  background: #fff;
  color: #152934;
}

pre[class*='language-']::-moz-selection,
pre[class*='language-'] ::-moz-selection,
code[class*='language-']::-moz-selection,
code[class*='language-'] ::-moz-selection {
  text-shadow: none;
  background: rgba(85, 150, 230 , .1);
}

pre[class*='language-']::selection,
pre[class*='language-'] ::selection,
code[class*='language-']::selection,
code[class*='language-'] ::selection {
  text-shadow: none;
  background: rgba(85, 150, 230 , .1);
}

/* Code blocks */
pre[class*='language-'] {
  padding: 1em;
  overflow: auto;
}

/* Inline code */
:not(pre) > code[class*='language-'] {
  padding: 0.1em;
  border-radius: 0.3em;
}

.token.comment,
.token.prolog,
.token.doctype,
.token.cdata {
  color: #898ea4;
}

.token.punctuation {
  color: #687985;
}

.token.operator {
  color: #687985;
}

.token.boolean,
.token.number {
  color: #006456;
}

.token.property {
  color: #97702d;
}

.token.tag {
  color: #687985;
}

.token.string {
  color: #2D74DA;
}

.token.selector {
  color: #5A3EC8;
}

.token.attr-name {
  color: #2D74DA;
}

.token.entity,
.token.url,
.language-css .token.string,
.style .token.string {
  color: #2D74DA;
}

.token.attr-value,
.token.keyword,
.token.control,
.token.directive,
.token.unit {
  color: #5b8121;
}

.token.statement,
.token.regex,
.token.atrule {
  color: #006456;
}

.token.placeholder,
.token.variable {
  color: #831B4C;
}

.token.deleted {
  text-decoration: line-through;
}

.token.inserted {
  border-bottom: 1px dotted #c22dd5;
  text-decoration: none;
}

.token.italic {
  font-style: italic;
}

.token.important,
.token.bold {
  font-weight: bold;
}

.token.important {
  color: #c94922;
}

.token.entity {
  cursor: help;
}

pre > code.highlight {
  outline: 0.4em solid #c94922;
  outline-offset: 0.4em;
}

/* overrides color-values for the Line Numbers plugin
 * http://prismjs.com/plugins/line-numbers/
 */
.line-numbers .line-numbers-rows {
  border-right-color: #687985;
}

.line-numbers-rows > span:before {
  color: #687985;
}

/* overrides color-values for the Line Highlight plugin
 * http://prismjs.com/plugins/line-highlight/
 */
.line-highlight {
  background: rgba(107, 115, 148, 0.2);
  background: -webkit-linear-gradient(
    left,
    rgba(107, 115, 148, 0.2) 70%,
    rgba(107, 115, 148, 0)
  );
  background: linear-gradient(
    to right,
    rgba(107, 115, 148, 0.2) 70%,
    rgba(107, 115, 148, 0)
  );
}
```

**Comment by alisonjoseph** [comment]
@tay-aitken This would be a separate PR from the code snippet work since this lives in the website and not in the core components. 

I'll also create a codepen with the new code snippet styles (once v9 is live) and an example using these colors for the highlighting and line numbers.

**Comment by tay-aitken** [comment]
Great! I'll add the website based code in one of my PRs, thanks @alisonjoseph!
