### ISSUE TITLE
Code Pen links in Add-Ons are not working

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/design-system-website#132]
The Code Pen links in the `Card` & `Detail Page Header` Add Ons section link to a `404` page.

**OS:** Win 10
**Browser:** Chrome v63.0.3239.132 (Official Build) (64-bit)

> What did you expect to happen? What happened instead? What would you like to see changed?

It should link to the correct Code Pen page.

### Screenshot

![image](https://user-images.githubusercontent.com/6926228/34887812-d081ba54-f795-11e7-806f-a4ef47c108e0.png)

**Comment by marijohannessen** [comment]
Hi! Thanks for opening this issue. Will get a fix in for this as soon as possible!
