### ISSUE TITLE
Type Bug: Missing colon at inline notifications

### ISSUE THREAD

**Issue by havesomeleeway** [carbon-design-system/design-system-website#138]
### On the site

![screenshot-2018-1-20 carbon design system](https://user-images.githubusercontent.com/25948209/35178982-0798cec4-fdcc-11e7-9d63-fe05b79d4136.png)

### On Sketch

![screen shot 2018-01-20 at 10 24 14 am](https://user-images.githubusercontent.com/25948209/35178988-1d3393e0-fdcc-11e7-8e3d-fb0527aa73e5.png)

**Comment by marijohannessen** [comment]
Hi @havesomeleeway , thanks for creating this issue! This needs to be updated in the actual component since we're just pulling them directly from the repo, so I'm going to move this issue over to that repo. Thanks!

**Comment by marijohannessen** [comment]
Issue moved to [carbon-design-system/carbon-components #519](https://github.com/carbon-design-system/carbon-components/issues/519) via [**ZenHub**](https://www.zenhub.com/)
