### ISSUE TITLE
Lacking documentation for two-column form layout

### ISSUE THREAD

**Issue by creuter** [carbon-design-system/design-system-website#139]
Hello!

The `form` component's [structure documentation](http://carbondesignsystem.com/components/form/style#stucture) (as well as the design kit layout templates) describe a two-column layout for form items, but there are no markup examples.

They don't work well for with the `grid` styling, and it's not clear how that layout is intended to happen.

**Comment by marijohannessen** [comment]
@aagonzales Do you have an example of how the forms should work within our grid?

**Comment by aagonzales** [comment]
Yes, there is an example on the page linked in the original example and also examples in the design kit.

![image](https://user-images.githubusercontent.com/11670886/35233221-17b40452-ff63-11e7-9c33-cd5bf7148021.png)

**Comment by aagonzales** [comment]
Example of how a form could respond:
![image](https://user-images.githubusercontent.com/11670886/39656892-ead7b8d2-4fc8-11e8-8520-ebe5a9c3362f.png)

@carbon-design-system/ui can we maybe get a codepen example of a responsive 2 column form and some dev docs around how to collapse a 2 column form into a single column.

**Comment by tay-aitken** [comment]
@aagonzales can we close this issue?

**Comment by aagonzales** [comment]
Yes, can close for now. I think it would be nice to have a Codepen example of 2 column form. Maybe we can make it a hacktime project.
