### ISSUE TITLE
Component not responsiding correctly on website

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/design-system-website#158]
## Detailed description

The detail page is not responding correctly on the Add-on page. The tabs disappear on small pages but should respond down to a dropdown.

## What it currently is doing:
![image](https://user-images.githubusercontent.com/11670886/35873445-58b91d34-0b2f-11e8-88ad-58b528193308.png)

![image](https://user-images.githubusercontent.com/11670886/35873465-616089c2-0b2f-11e8-88af-be0b612f5904.png)

## What it should be doing:
![image](https://user-images.githubusercontent.com/11670886/35873502-7e73a86e-0b2f-11e8-8ada-08ce962915d5.png)

**Comment by marijohannessen** [comment]
This seems to be fixed - please re-open if you still see the issue @aagonzales !
