### ISSUE TITLE
Is table element responsive?

### ISSUE THREAD

**Issue by kprathapk** [carbon-design-system/design-system-website#172]
<!-- Feel free to remove sections that aren't relevant.

## Title line template: [Title]: Brief description
It seems that tables are not responsive on small screens?

**Comment by tw15egan** [comment]
Yes, to an extent. There is no mobile data-table. You can see an example of this here https://codepen.io/team/carbon/pen/pdWjva and more extensive guidelines here http://www.carbondesignsystem.com/components/data-table/code
