### ISSUE TITLE
Danger Buttons Updates

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/design-system-website#173]
@tay-aitken commented on [Thu Feb 08 2018](https://github.com/carbon-design-system/carbon-components/issues/548)

- [ ] Remove the `small button with icon` and `button with icon` from the danger button section of the buttons page.
- [ ] Add in `primary danger button` only (not the icon based one) as well as `small primary`

**Comment by tw15egan** [comment]
I removed them from the HTML in the vanilla repo, so is this already done since the examples on the site are generated from those HTML files?

**Comment by marijohannessen** [comment]
You're right! I'll make sure it looks okay before deploying later today :-)
