### ISSUE TITLE
Add inline dropdown to Dropdown page

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/design-system-website#177]
Please add the inline dropdown to the Dropdown page. For some reason it is appearing in the [react library](http://react.carbondesignsystem.com/?selectedKind=DropdownV2&selectedStory=inline&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) but not the website.

**Comment by marijohannessen** [comment]
It seems like it's missing from the vanilla repo 😱 I created an issue to get it added, and then I'll update this issue once it's on the website.
