### ISSUE TITLE
Link in readme.md doesn't work

### ISSUE THREAD

**Issue by willowbrae** [carbon-design-system/design-system-website#182]
Link in _readme.md_ to the Carbon site doesn't work, probably adding _http://_ in front of it will solve the issue.

**Comment by asudoh** [comment]
Hi @willowbrae thank you for reporting! One quick question, which browser are you using?

**Comment by willowbrae** [comment]
@asudoh I'm using Chrome.

**Comment by willowbrae** [comment]
@bsonefeld Working fine, thanks!
