### ISSUE TITLE
Carbon site - Structured list's header details are not up to date

### ISSUE THREAD

**Issue by willowbrae** [carbon-design-system/design-system-website#183]
On the website it says that column header's font size should be 12px Omega, but examples on the same page (when inspected) are using 14px.

http://www.carbondesignsystem.com/components/structured-list/style

**Comment by marijohannessen** [comment]
Thanks for making this issue @willowbrae ! @bsonefeld is the information on the website incorrect or do we need to update this in the component itself? If so, I'll move this issue over to `carbon-components`.

**Comment by bsonefeld** [comment]
Looks like it's a bug in the code- just double checked with the visual specs.

**Comment by tay-aitken** [comment]
Closing as this will fixed in this [PR](https://github.com/carbon-design-system/carbon-components/pull/766). Thanks for bringing this to our attention @willowbrae!
