### ISSUE TITLE
Missing hint text / error styling for Text-Input element 

### ISSUE THREAD

**Issue by willowbrae** [carbon-design-system/design-system-website#189]
I can't find styling details for hint text /  error below the input field. What size, weight, line-height and colour is the text and how big margin is between these elements. Would be cool to add it to the guidelines.

I checked here:
http://carbondesignsystem.com/components/form/style
http://carbondesignsystem.com/components/text-input/style

**Comment by aagonzales** [comment]
@willowbrae Good catch! We will work on adding on to the website but for now you can check the assets in the kit.

**Comment by tay-aitken** [comment]
Addressing this in an internal repo. Documentation for this will be out on June 1st. Thanks for opening an issue :)
