### ISSUE TITLE
Carbon site — Same selector doing different tasks 

### ISSUE THREAD

**Issue by qqpin** [carbon-design-system/design-system-website#191]
In Notification component, the same selector are doing different tasks. Maybe the other 4s are actually for inline notifications, but labeling incorrectly. 

![screen shot 2018-04-19 at 3 17 03 pm](https://user-images.githubusercontent.com/14185008/39013236-c7da7760-43e4-11e8-9205-befe17340f6c.png)

**Comment by asudoh** [comment]
I see [inline notification](https://github.com/carbon-design-system/carbon-components/blob/bd8e5c9/src/components/notification/_inline-notification.scss#L31-L45) as well as [toast notification](https://github.com/carbon-design-system/carbon-components/blob/7b70758/src/components/notification/_toast-notification.scss#L36-L50) have `--error`, etc. modifier classes. Therefore I guess the table should be split into two, though I need @tw15egan and @marijohannessen to confirm.

**Comment by alisonjoseph** [comment]
Correct @asudoh these should be split into two tables and the first four have the incorrect class name. I created a PR in `carbon-components` to fix. https://github.com/carbon-design-system/carbon-components/pull/723
