### ISSUE TITLE
Display latest version of the vanilla and the React repos on the website

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/design-system-website#217]
Add information about the latest versions of both the React repo and the vanilla repo.

**Comment by tay-aitken** [comment]
This is now being shown on the site. Closing.
<img width="337" alt="screen shot 2018-06-24 at 9 53 04 pm" src="https://user-images.githubusercontent.com/29312997/41828113-047cd56c-77f9-11e8-9420-1e0973d16c70.png">
