### ISSUE TITLE
Left hand navigation color link is dead

### ISSUE THREAD

**Issue by ExiliumAeternum** [carbon-design-system/design-system-website#234]
## Detailed description

The left hand nav link for colors is dead

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the link I click on to load

> What browser are you working in?

Chrome

## Steps to reproduce the issue

1. Go to carbon website
2. Search 'color' in left hand nav
3. click on the top result, colors
4. notice that the link in the url bar changed, but it doesn't load

**Comment by tw15egan** [comment]
@marijohannessen link should route to `color`, seems it is currently pointing to `colors`

**Comment by marijohannessen** [comment]
This is fixed on the v9 version of the website which will be released tomorrow.

**Comment by tw15egan** [comment]
🥇
