### ISSUE TITLE
V9 Audit

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/design-system-website#237]

**Comment by marijohannessen** [comment]
- [ ] Update text color on Glossary page:
<img width="852" alt="screen shot 2018-05-31 at 11 29 04 am" src="https://user-images.githubusercontent.com/5447411/40794813-e5866e3e-64c5-11e8-9e0f-415bc15a4e2a.png">

**Comment by aagonzales** [comment]
- [ ] Update line length max on Glossary page (max width 38 rem)

**Comment by tay-aitken** [comment]
- [ ] iconography > usage > icon images are blurry, does this have anything to do with the sizing?
- [ ] Colors > swatches > hover section > not copying hex codes but the information below it instead. The hex codes should be the following:
  - danger #BD1427
  - primary #30588C
  - primary-text #294C86
  - row #5596E6 at 10% opacity
  - secondary #3D70B2

**Comment by tay-aitken** [comment]
- [ ] Getting started > add-ons > carbon support & contributing to add-ons > swap to carbon success checkmark
- [ ] FAQ > I haven't updated to the latest version...question > need to add a link to the V8 site once we have the URL for that.
- [ ] Guidelines > Content > Dos & Donts > checkmarks and x's need to be updated to the new icon style
- [ ]

**Comment by tay-aitken** [comment]
- [ ] inline code snippet code pen link is going to terminal snippet code pen page 
- [ ] data tables > toolbar > search icon is getting ever so slightly cut off
<img width="113" alt="screen shot 2018-05-31 at 12 39 12 pm" src="https://user-images.githubusercontent.com/29312997/40798039-b2181642-64cf-11e8-983d-8e53bcaee1bd.png">
- [ ] data table with pagination > is not using the proper icons > @alisonjoseph is that what you were fixing earlier?
- [ ] data table > style > first and second images needs a border outline

**Comment by alisonjoseph** [comment]
Yes @tay-aitken the data table icon updates are in this PR https://github.com/carbon-design-system/carbon-components/pull/826

**Comment by tay-aitken** [comment]
- [ ] date picker > style > first image needs an outline
- [ ] date picker usage > gif needs to be shrunk and given a background of ui-02

**Comment by aagonzales** [comment]
- [ ] Filter dropdown needs field options?
<img width="1009" alt="screen shot 2018-05-31 at 1 38 55 pm" src="https://user-images.githubusercontent.com/11670886/40801213-fe246b14-64d7-11e8-9f41-5aef2eb8689b.png">

**Comment by alisonjoseph** [comment]
- [ ] Primary danger and small primary danger buttons are missing from the website, is this on purpose?

**Comment by tay-aitken** [comment]
- [ ] data vis > tooltip > style > it looks like we were trying to scale down the overall image size but maybe it wasnt spaced correctly in the code?

<img width="692" alt="screen shot 2018-05-31 at 2 18 47 pm" src="https://user-images.githubusercontent.com/29312997/40803218-ab3b9b10-64dd-11e8-96de-18afcede6626.png">
