### ISSUE TITLE
The deprecation banner on the V8 site doesn't display correctly

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/design-system-website#255]
The banner is underneath the hamburger menu, which makes sense, but because the hamburger menu is open by default, and banner is unreadable when first arriving on the site, and it's not obvious the user should close the menu to read it. 

![image](https://user-images.githubusercontent.com/6569324/40989222-c3d68fe4-68b2-11e8-9805-29768d199cc8.png)

The banner should probably react to the menu opening, or placed/styled in such a way that the text is legible even with the menu open. Or the menu should be closed by default.

**Comment by marijohannessen** [comment]
Thanks for letting us know, we'll deploy a fix!

**Comment by marijohannessen** [comment]
Fixed in #261
