### ISSUE TITLE
Spelling errors in screen snap of interactive tooltip

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/design-system-website#256]
On the [tooltip usage page](http://www.carbondesignsystem.com/components/tooltip/usage), the interactive tooltip example screenshot has multiple spelling errors (and it should probably be redone).
- uniques -> unique
- Storgae -> Storage
- loacations -> locations

images/tooltip-usage-3.png

**Comment by tay-aitken** [comment]
Is being resolved in PR #258
