### ISSUE TITLE
Skip link doesn't work

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/design-system-website#263]
The skip link on each Carbon Design System website page doesn't work.

- Start in the browser's address bar, and type Tab until you see the skip link.
- Type Enter to follow the link and give focus to the main region.
- Nothing happens.

I will submit a PR for this - not sure if you prefer to have an issue as well?

**Comment by marijohannessen** [comment]
This issue is enough for tracking, thanks for helping us out! 🙂 🙌

**Comment by carmacleod** [comment]
You're welcome. I was wondering if just the PR by itself was enough for tracking.
Since I wasn't sure, I opened this issue.  :)
