### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chaseoli** [carbon-design-system/design-system-website#278]
See docs at: http://www.carbondesignsystem.com/getting-started/developers/vanilla
in the text: 

> Allows you to access public methods (found in our components page, e.g. here for modal) via the instance reference (modalInstance.show(), etc. in above example)

The _here_ link refs localhost:300 - looks like an accidental push with a dev root 
`<a href="http://localhost:3000/components/modal/code#public-methods">here</a>`

**Comment by marijohannessen** [comment]
Oops, thanks for letting us know! Will be sure to fix asap :)
