### ISSUE TITLE
Old Text Input style in Theming Sandbox

### ISSUE THREAD

**Issue by willowbrae** [carbon-design-system/design-system-website#279]
Text Input style in Theming Sandbox doesn't reflect the newest style. 

http://carbondesignsystem.com/components/text-input/code
vs
http://themes.carbondesignsystem.com/

**Comment by tay-aitken** [comment]
@tw15egan was this addressed when you updated the theme sandbox?

**Comment by tw15egan** [comment]
Yes this has been updated
