### ISSUE TITLE
Left Nav: Closing inner accordion closes outer accordion

### ISSUE THREAD

**Issue by goanalog** [carbon-design-system/design-system-website#57]
## Detailed description

When using left nav and expanding inner accordion for "Data Vis," everything works great when you select the text labels. 

When you select the triangle itself, however, things get wacky. A selection of the _inner_ triangle closes the _outer_ accordion! Seems like maybe it's treating all the triangles the same?

Example:

![oct-17-2017 13-14-51](https://user-images.githubusercontent.com/1304979/31682014-6eef0c9c-b33e-11e7-9f39-ccb833d3d93f.gif)

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the inner accordion to only impact the inner accordion, and the outer to only be impacted by itself. 

Instead, the inner accordion controls impacted the _outer_ accordion controls. 

I'd prefer this didn't happen. 

> What browser are you working in?

Chrome 60.0.3112.113 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

Current website

## Steps to reproduce the issue

1. Navigate to carbondesignsystem.com
2. Open "Components" accordion in left nav
3. Select triangle next to "Data Vis" within "Components" section of nav
4. Be amazed

**Comment by tay-aitken** [comment]
Thanks for letting us know about the issue @goanalog! Appreciate it 😊

**Comment by goanalog** [comment]
Any time! Congratulations on Carbon 8 :)

**Comment by marijohannessen** [comment]
Resolved and will be part of the deployment tonight!
