### ISSUE TITLE
Typo: In nav, "Add-on's" shouldn't have an apostrophe

### ISSUE THREAD

**Issue by joshkimmell** [carbon-design-system/design-system-website#74]
## Steps to reproduce the issue

1. Go to http://carbondesignsystem.com/
2. Look at the side nav
3. Notice that it says "Add-on's"
4. Realize that it shouldn't be the possessive

## Additional information

![image](https://user-images.githubusercontent.com/8161298/32114899-68142c12-bb0a-11e7-90de-55a31c979841.png)

**Comment by cknabe** [comment]
Fixed in #75
