### ISSUE TITLE
[Bug] InteriorLeftNav still shows up in Search

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/design-system-website#82]
Hi there! 👋  😄 

Noticed tonight that `InteriotLeftNav` stills show up in the search bar on the site, clicking it unfortunately causes some React breakage 😞 

![screen shot 2017-11-07 at 9 05 11 pm](https://user-images.githubusercontent.com/3901764/32529701-962a199c-c3ff-11e7-9493-1b716c1b6bb3.png)

**Comment by marijohannessen** [comment]
Ooof will fix!
