### ISSUE TITLE
Motion Page Examples

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/design-system-website#96]
## Overview
Email from Paulo Catumba:
I noticed that on the videos that represent the different easings, the blue squares are actually all animating with the standard 'cubic-bezier' when they should be 'ease-in' and 'ease-out'
http://carbondesignsystem.com/style/motion

**Comment by marijohannessen** [comment]
Closing this as they are all animating with `cubic-bezier`, but `cubic-bezier` is set to mimic `ease-in` and `ease-out`. They are all in fact with different values.
